using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaleFlex.Data
{
    // Enum representing different types of forms used in the system.
    public enum EnumFormType
    {
        NONE = 0,           // No form selected.
        SALE = 1,           // Sale transaction form.
        LOGIN,              // Login form.
        LOGIN_EXT,          // Extended login form.
        LOGIN_SERVICE,      // Service login form.
        SERVICE,            // Service-related form.
        SETTING,            // Settings configuration form.
        PARAMETER,          // Parameter configuration form.
        REPORT,             // Report form.
        FUNCTION,           // Function selection form.
        CUSTOMER,           // Customer-related form.
        VOID,               // Form for voiding a transaction.
        REFUND,             // Refund transaction form.
        STOCK,              // Stock management form.
        END_OF_DAY,         // End-of-day process form.
        TABLE,              // Table management form (e.g., for restaurants).
        ORDER,              // Order management form.
        CHECK,              // Check payment form.
        EMPLOYEE,           // Employee management form.
        RESERVATION,        // Reservation form.
        WAREHOUSE           // Warehouse form.
    }

    // Enum representing different types of payment methods.
    public enum EnumPaymentType
    {
        NONE = 0,           // No payment type selected.
        CASH = 1,           // Cash payment.
        CREDIT_CARD = 2,    // Payment using a credit card.
        CHECK = 3,          // Payment using a check.
        CREDIT_NOCARD = 4,  // Credit payment without a physical card (account-based).
        PREPAID_CARD = 5,   // Prepaid card payment.
        MOBILE = 6,         // Mobile payment (e.g., digital wallets).
        BONUS = 7,          // Payment using bonus points or rewards.
        EXCHANGE = 8,       // Exchange or barter-based payment.
        ON_CREDIT = 9,      // On-credit payment (VERESİYE).
        OTHER = 10          // Other unspecified payment methods.
    }

    // Enum representing the state of a document (e.g., receipt or invoice).
    public enum EnumDocumentState
    {
        CLOSED,         // The document has been finalized and closed.
        SUSPENDED,      // The document is suspended and waiting to be resumed.
        OPENED          // The document is open and still in progress.
    }

    // Enum representing the result of a document transaction.
    public enum EnumDocumentResult
    {
        NONE = 0,                                               // No result specified.
        SUCCEEDED,                                              // The transaction or document completed successfully.
        CANCELED_BY_CASHIER,                                    // The transaction was canceled by the cashier.
        CANCELED_BY_APPLICATION,                                // The transaction was canceled by the system.
        CANCELED_BY_APPLICATION_AFTER_POWER_ON,                 // Canceled after a power failure during the transaction.
        CANCELED_BY_APPLICATION_BECAUSE_OF_HANGING,             // Canceled because the document was left in a suspended state for too long.
        SUSPENDED,                                              // The transaction has been suspended and left on hold.
        FAILED                                               
    }

    // Enum representing different types of documents generated by the system.
    public enum EnumDocumentType
    {
        None = 0,                   // No document type.
        FiscalReceipt,               // Fiscal receipt (required for tax purposes).
        NoneFiscalReceipt,           // Non-fiscal receipt (not for tax purposes).
        Invoice,                     // Standard paper invoice.
        EInvoice,                    // Electronic invoice.
        EArchiveInvoice,             // Electronic archived invoice.
        DiplomaticInvoice,           // Invoice for diplomatic sales.
        Waybill,                     // Transportation or delivery document.
        DeliveryNote,                // Delivery note or slip.
        CashOutflow,                 // Document recording cash outflow (expenses).
        CashInflow,                  // Document recording cash inflow (income).
        Return,                      // Document for returned items or transactions.
        SelfBillingInvoice           // Self-billing invoice (Gider Pusulası in Turkish).
    };

    // Enum representing different error codes used in the system.
    public enum EnumErrorCode
    {
        NONE = 0,                            // No error occurred.
        DEPARTMENT_NOT_FOUND = 1,            // The specified department could not be found.
        CAN_NOT_INSERT_TRANSACTION,          // The system failed to insert the transaction.
        CAN_NOT_START_RECEIPT,               // The system could not start the receipt process.
        NEED_CASHIER_LOGIN,                  // Cashier login is required to proceed.
        CASHIER_LOGIN_FAILED,                // Cashier login attempt failed.
        PLU_NOT_FOUND,                       // Product Lookup (PLU) code was not found.
        INSUFFICIENT_STOCK,                  // Insufficient stock to complete the transaction.
        CAN_NOT_CLOSE_RECEIPT,               // The receipt could not be closed.
        PAYMENT_TYPE_ERROR,                  // Error related to the payment type.
        PAYMENT_NOT_POSSIBLE,                // Payment could not be processed.
        CAN_NOT_CANCEL_TRANSACTION,          // The system could not cancel the transaction.
        CAN_NOT_CANCEL_DOCUMENT,             // The system could not cancel the document.
        SUBTOTAL_NOT_POSSIBLE,               // The system could not calculate the subtotal.
        SUSPEND_QUEUE_FULL,                  // The queue for suspended transactions is full.
        SUSPEND_NOT_FOUND,                   // The suspended transaction could not be found.
        NEED_SUSPEND,                        // The transaction needs to be suspended.
        CLOSURE_NOT_POSSIBLE                 // The system could not perform the closure process.
    }

    // Enum representing units of measurement for stock items.
    public enum EnumStockUnit
    {
        PC = 1,              // Pieces (individual items).
        GRAM = 1,            // Grams for measuring weight.
        KG = 1000,           // Kilograms for larger weight measurement (1,000 grams).
        LITER = 1000,        // Liters for liquid measurements.
        METER = 100          // Meters for length measurements.
    }
}
