
namespace SaleFlex.UserInterface.Constanst
{
    static public class CustomEventFunctionName
    {
        public const string strNone = "NONE";
        public const string strExitApplication = "EXIT_APPLICATION";
        public const string strLogin = "LOGIN";
        public const string strLoginExtended = "LOGIN_EXTENDED";
        public const string strLogout = "LOGOUT";
        public const string strServiceCodeRequest = "SERVICE_CODE_REQUEST";
        public const string strLoginService = "LOGIN_SERVICE";
        public const string strCloseForm = "CLOSE_FORM";
        public const string strSaveChanges = "SAVE_CHANGES";
        public const string strSaleDepartment = "SALE_DEPARTMENT";
        public const string strSaleDepartmentByNo = "SALE_DEPARTMENT_BY_NO";
        public const string strSalePluCode = "SALE_PLU_CODE";
        public const string strSalePluBarcode = "SALE_PLU_BARCODE";
        public const string strGetPluFromMainGroup = "GET_PLU_FROM_MAINGROUP";
        public const string strRepeatLastSale = "REPEAT_LAST_SALE";
        public const string strRepeatSale = "REPEAT_SALE";
        public const string strCancelDepartment = "CANCEL_DEPARTMENT";
        public const string strCancelPlu = "CANCEL_PLU";
        public const string strCancelLastSale = "CANCEL_LAST_SALE";
        public const string strCancelSale = "CANCEL_SALE";
        public const string strOpenCashDrawer = "OPEN_CASH_DRAWER";
        public const string strFunctionMenu = "FUNCTION_MENU";
        public const string strSaleMenu = "SALES_MENU";
        public const string strServiceMenu = "SERVICE_MENU";
        public const string strSettingMenu = "SETTING_MENU";
        public const string strReportMenu = "REPORT_MENU";
        public const string strCashier = "CASHIER";
        public const string strChangeDocumentType = "CHANGE_DOCUMENT_TYPE";
        public const string strCustomer = "CUSTOMER";
        public const string strRefund = "REFUND";
        public const string strDiscountByAmount = "DISCOUNT_BY_AMOUNT";
        public const string strSurchargeByAmount = "SURCHARGE_BY_AMOUNT";
        public const string strDiscountByPercent = "DISCOUNT_BY_PERCENT";
        public const string strSurchargeByPercent = "SURCHARGE_BY_PERCENT";
        public const string strInputPrice = "INPUT_PRICE";
        public const string strInputQuantity = "INPUT_QUANTITY";
        public const string strInputAmount = "INPUT_AMOUNT";
        public const string strPriceLookUp = "PRICE_LOOKUP";
        public const string strSubTotal = "SUBTOTAL";
        public const string strTotal = "TOTAL";
        public const string strSaleOption = "SALE_OPTION";
        public const string strClearBuffer = "CLEAR_BUFFER";
        public const string strPayment = "PAYMENT";                         // Payment Function        
        public const string strCashPayment = "CASH_PAYMENT";                // Payment Function
        public const string strCreditPayment = "CREDIT_PAYMENT";            // Payment Function
        public const string strCheckPayment = "CHECK_PAYMENT";              // Payment Function
        public const string strExchangePayment = "EXCHANGE_PAYMENT";        // Payment Function
        public const string strPrepaidPayment = "PREPAID_PAYMENT";          // Payment Function
        public const string strOtherPayment = "CHARGE_SALE_PAYMENT";        // Payment Function
        public const string strChargeSalePayment = "OTHER_PAYMENT";         // Payment Function
        public const string strPaymentDetail = "PAYMENT_DETAIL";
        public const string strCancelDocument = "CANCEL_DOCUMENT";
        public const string strClosure = "CLOSURE";
        public const string strStockEntryForm = "STOCK_ENTRY_FORM";
        public const string strSaleDetailReport = "SALE_DETAIL_REPORT";
        public const string strPluSaleReport = "PLU_SALE_REPORT";
        public const string strPosSummaryReport = "POS_SUMMARY_REPORT";
        public const string strSetDisplayBrightness = "SET_DISPLAY_BRIGHTNESS";
        public const string strSetPrinterIntensity = "SET_PRINTER_INTENSITY";
        public const string strSetCashier = "SET_CASHIER";
        public const string strSetSupervisor = "SET_SUPERVISOR";
        public const string strSetReceiptHeader = "SET_RECEIPT_HEADER";
        public const string strSetReceiptFooter = "SET_RECEIPT_FOOTER";
        public const string strSetIdleMessage = "SET_IDLE_MESSAGE";
        public const string strSetBarcodeDefinition = "SET_BARCODE_DEFINITION";
        public const string strSetVatDefinition = "SET_VAT_DEFINITION";
        public const string strSetDepartmentDefinition = "SET_DEPARTMENT_DEFINITION";
        public const string strSetCurrencyDefinition = "SET_CURRENCY_DEFINITION";
        public const string strSetPluDefinition = "SET_PLU_DEFINITION";
        public const string strSetPluMainGroupDefinition = "SET_PLU_MAINGROUP_DEFINITION";
        public const string strSetDiscountRate = "SET_DISCOUNT_RATE";
        public const string strSetSurchargeRate = "SET_SURCHARGE_RATE";
        public const string strServiceCompanyInfo = "SERVICE_COMPANY_INFO";
        public const string strServiceChangeDateTime = "SERVICE_CHANGE_DATE_TIME";
        public const string strServiceParameterDownload = "SERVICE_PARAMETER_DOWNLOAD";
        public const string strServiceSetReceiptLimit = "SERVICE_SET_RECEIPT_LIMIT";
        public const string strServiceResetToFactoryMode = "SERVICE_RESET_TO_FACTORY_MODE";
        public const string strServiceResetPassword = "SERVICE_RESET_PASSWORD";
        public const string strServiceChangePassword = "SERVICE_CHANGE_PASSWORD";
        public const string strServicePosActive = "SERVICE_POS_ACTIVE";
        public const string strServiceSoftwareDownload = "SERVICE_SOFTWARE_DOWNLOAD";
        public const string strInvoiceList = "INVOICE_LIST";
        public const string strWaybillList = "WAYBILL_LIST";
        public const string strReturnList = "RETURN_LIST";
        public const string strServiceGetPluList = "SERVICE_GET_PLU_LIST";
        public const string strStockLookUp = "STOCK_LIST";
        public const string strSuspendPayment = "SUSPEND_PAYMENT";
        public const string strBackPayment = "BACK_PAYMENT";
        public const string strSaleShortcut = "SALE_SHORTCUT";
        public const string strReDrawForm = "REDRAW_FORM";
    }
}
